# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a16ac15b9de16d1b0d68113b238167b6a6dcda76621b206764bdfafd32e737627fefa7cb009523d9f797893930e845ddb1ca0030734a84aa11d3e5d38594ffaf

test:
  secret_key_base: c26598fca178645be745005d63dfb60abc60fa69408b1c2446d885d312615161bc138010699fac89485c92fc251ffc1de24fa1b43f394c3859611d41906ddcae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
